### PR TITLE
Some minor fixes

### PR DESCRIPTION
**Pull request by ppanagiotis**

### CODE REVIEW

**Comment by lance36** [comment]
I'm Ok with the retain and the removal of the clean since it's unused, but why are you using getFormattedDate(); instead of getFullFormattedTime(); ?

**Comment by ppanagiotis** [comment]
The reason is [here](https://github.com/arduino-libraries/NTPClient/issues/36#issuecomment-334282081)

**Comment by lance36** [comment]
So it will require a fork of NTPClient ?

**Comment by ppanagiotis** [comment]
If I am correct you already use a fork of NTPClient. 
NTPClient doesn't support getFullFormattedTime()

**Comment by lance36** [comment]
Right, ok.
I'll merge the PR, but I'am unable to test it right now.
I'll also update the readme to point to the ntpclient fork (https://github.com/taranais/NTPClient/releases)

I'm also wondering if there is a more elegant way to publish the time, maybe leveraging some templating from home-assistant and not having to use ntp

**Comment by ppanagiotis** [comment]
:+1:

**Comment by lance36** [comment]
Thanks!  :)

**Pull request merged**
